# Preprocessing datasets

In [9]:
import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestClassifier 
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
import pickle

In [10]:
student_data=pd.read_csv("student_dataset/student-mat.csv")
student_data

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,4,3,4,1,1,3,6,5,6,6
1,GP,F,17,U,GT3,T,1,1,at_home,other,...,5,3,3,1,1,3,4,5,5,6
2,GP,F,15,U,LE3,T,1,1,at_home,other,...,4,3,2,2,3,3,10,7,8,10
3,GP,F,15,U,GT3,T,4,2,health,services,...,3,2,2,1,1,5,2,15,14,15
4,GP,F,16,U,GT3,T,3,3,other,other,...,4,3,2,1,2,5,4,6,10,10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
390,MS,M,20,U,LE3,A,2,2,services,services,...,5,5,4,4,5,4,11,9,9,9
391,MS,M,17,U,LE3,T,3,1,services,services,...,2,4,5,3,4,2,3,14,16,16
392,MS,M,21,R,GT3,T,1,1,other,other,...,5,5,3,3,3,3,3,10,8,7
393,MS,M,18,R,LE3,T,3,2,services,other,...,4,4,1,3,4,5,0,11,12,10
394,MS,M,19,U,LE3,T,1,1,other,at_home,...,3,2,3,3,3,5,5,8,9,9

## Transfer the target classification into two types and categorize the data type

In [11]:
student_data.drop(columns=["G1","G2","school","address"],inplace=True) #comment: why remove school and address?
student_data.rename(columns={'G3':'target'},inplace=True)
student_data["target"]=student_data["target"].apply(lambda x: 1 if x>=10 else 0) # translate the classes into two tpye: pass: 1 or fail: 0.

numeric_features=[i for i in student_data.columns if student_data[i].dtype in [np.int64, np.int64]]
categorical_features = [col for col in student_data.columns if col not in numeric_features]

feature_order=['sex', 'age', 'famsize', 'Pstatus', 'Medu', 'Fedu', 'traveltime',
       'studytime', 'failures', 'schoolsup', 'famsup', 'paid', 'activities',
       'nursery', 'higher', 'internet', 'romantic', 'famrel', 'freetime',
       'goout', 'Dalc', 'Walc', 'health', 'absences', 'guardian_father',
       'guardian_mother', 'guardian_other', 'Fjob_at_home', 'Fjob_health',
       'Fjob_other', 'Fjob_services', 'Fjob_teacher', 'reason_course',
       'reason_home', 'reason_other', 'reason_reputation', 'Mjob_at_home',
       'Mjob_health', 'Mjob_other', 'Mjob_services', 'Mjob_teacher','target']
# this is prepared for later use of the encoded dataset; the column names
# By default, pd.get_dummies() orders the new one-hot encoded columns alphabetically based on the unique values in the categorical column. That's why we know whcih column is for which value.

A short test aboout the output of the following binary_mappings function

In [12]:
student_data['sex'] = student_data['sex'].astype('category')
print(student_data['sex'].cat.categories)
print(enumerate(student_data['sex'].cat.categories))
print(dict(enumerate(student_data['sex'].cat.categories)))

Index(['F', 'M'], dtype='object')
<enumerate object at 0x000001988F0F57C0>
{0: 'F', 1: 'M'}

## Encoding and run model

In [13]:
randomstate=123

def encode_features(df, categorical_features):
    binary_mappings = {}
    for feature in categorical_features:
        unique_values = df[feature].nunique()
        if unique_values == 2:
            # Binary encoding
            df[feature] = df[feature].astype('category') 
            mapping = dict(enumerate(df[feature].cat.categories)) 
            binary_mappings[feature] = {v: k for k, v in mapping.items()} 
            df[feature] = df[feature].map(binary_mappings[feature])
            df[feature] = df[feature].astype('int')
        else:
            # One-hot encoding
            one_hot = pd.get_dummies(df[feature], prefix=feature, dtype="int")
            df = df.drop(feature, axis=1)
            df = pd.concat([df, one_hot], axis=1)
    return df, binary_mappings

# Apply encoding
student_data , binary_mappings= encode_features(student_data, categorical_features)

#Move target to end
target_col = student_data.pop("target") # pop(), remove the target colum.
student_data.insert(len(student_data.columns), "target", target_col) # syntax: DataFrame.insert(location, column_name, values)

In [14]:
#Create and save final train/test sets with target being the last column
student_data=student_data[feature_order]
student_train,student_test = train_test_split(student_data, test_size=0.2 , random_state=randomstate)

student_train.to_parquet("student_dataset/train_cleaned_y.parquet")
student_test.to_parquet("student_dataset/test_cleaned_y.parquet")

x_train = student_train.drop("target", axis=1)
y_train= student_train["target"]

x_test=student_test.drop("target", axis=1)
y_test=student_test["target"]

model = RandomForestClassifier(n_estimators=100, random_state=randomstate)
# model=GaussianNB()

model.fit(x_train, y_train)

target_pred = model.predict(x_test)

accuracy = accuracy_score(y_test, target_pred)
print(f"Accuracy: {accuracy * 100:.2f}%")

Accuracy: 78.48%

Saves (serializes) the model object to a file named RF.pkl using the pickle module.

In [15]:
with open('student_dataset/RF.pkl', 'wb') as f:
    pickle.dump(model, f) #pickle.dump(object_to_save, file)

In [16]:
x_train.columns

Index(['sex', 'age', 'famsize', 'Pstatus', 'Medu', 'Fedu', 'traveltime',
       'studytime', 'failures', 'schoolsup', 'famsup', 'paid', 'activities',
       'nursery', 'higher', 'internet', 'romantic', 'famrel', 'freetime',
       'goout', 'Dalc', 'Walc', 'health', 'absences', 'guardian_father',
       'guardian_mother', 'guardian_other', 'Fjob_at_home', 'Fjob_health',
       'Fjob_other', 'Fjob_services', 'Fjob_teacher', 'reason_course',
       'reason_home', 'reason_other', 'reason_reputation', 'Mjob_at_home',
       'Mjob_health', 'Mjob_other', 'Mjob_services', 'Mjob_teacher'],
      dtype='object')

In [17]:
feature_desc = [
    "The sex of the student as a binary variable (0: female, 1: male)",
    "The age of the student in years",
    "Size of the family of the student (0: greater than 3 , 1 : less than 3)",
    "Parents cohabitation status (0: living apart, 1: living together)",
    "Mother's education (0: none, 1: primary education (4th grade), 2: 5th to 9th grade, 3: secondary education or 4: higher education)",
    "Father's education (0: none, 1: primary education (4th grade), 2: 5th to 9th grade, 3: secondary education or 4: higher education)",
    "Home to school travel time (1: <15 min, 2: 15 to 30 min., 3: 30 min. to 1 hour, or 4: >1 hour)",
    "Weekly study time (1: <2 hours, 2: 2 to 5 hours, 3: 5 to 10 hours, or 4: >10 hours)",
    "Number of past class failures (from 0 to 3)",
    "Student receiving extra educational support (0: no, 1:yes)",
    "Student receiving family educational support (0: no, 1: yes)",
    "Student taking extra paid classes within the course subject (0: no, 1:yes)",
    "Stdent taking part in extra-curricular activities (0:no, 1:yes)",
    "Student has attended nursery school (0:no, 1:yes)",
    "Student wants to get higher education (0:no, 1:yes)",
    "Student has internet access at home (0:no, 1:yes)",
    "Student is in a romantic relationship (0:no, 1:yes)",
    "Quality of family relationships (numeric: from 1 - very bad to 5 - excellent)",
    "Free time after school (from 1 - very low to 5 - very high)",
    "Going out with friends (from 1 - very low to 5 - very high)",
    "Workday alcohol consumption (from 1 - very low to 5 - very high)",
    "Weekend alcohol consumption (from 1 - very low to 5 - very high)",
    "Current health status (from 1 - very bad to 5 - very good)",
    "Number of school absences (actual number of absences)",
    "One-hot variable for student's guardian -- father is guardian",
    "One-hot variable for student's guardian -- mother is guardian",
    "One-hot variable for student's guardian -- neither mother or father but someone else is guardian",
    "One-hot variable for father's job -- at home",
    "One-hot variable for father's job -- care related",
    "One-hot variable for father's job -- other",
    "One-hot variable for father's job -- civil services",
    "One-hot variable for father's job -- teacher",
    "One-hot variable for reason to choose this school -- chosen for course offer",
    "One-hot variable for reason to choose this school -- chosen due to proximity to home",
    "One-hot variable for reason to choose this school -- chosen for some other reason",
    "One-hot variable for reason to choose this school -- chosen for school reputation",
    "One-hot variable for mothers's job -- at home",
    "One-hot variable for mothers's job -- care related",
    "One-hot variable for mothers's job -- other",
    "One-hot variable for mothers's job -- civil services",
    "One-hot variable for mothers's job -- teacher",
    ]

feature_desc_df = pd.DataFrame({
    "feature_name": list(x_test.columns),
    "feature_average": x_train.mean().to_list() ,
    "feature_desc": feature_desc,
})

dataset_description="The dataset contains information about students from two Portugese high schools and in particular their family situation and other habits"
target_description="The target variable represents the final year grade, transformed into whether the student passed (1) or not (0) at the end of the year"
task_description="Predict whether a student will pass"

dataset_info={
 "dataset_description": dataset_description,
 "target_description": target_description,
 "task_description": task_description,
 "feature_description": feature_desc_df
 }


with open('student_dataset/dataset_info', 'wb') as f:
    pickle.dump(dataset_info, f) #pickle.dump(object_to_save, file)

In [18]:
feature_desc_df

,feature_name,feature_average,feature_desc
0,sex,0.458861,The sex of the student as a binary variable (0...
1,age,16.756329,The age of the student in years
2,famsize,0.294304,Size of the family of the student (0: greater ...
3,Pstatus,0.892405,"Parents cohabitation status (0: living apart, ..."
4,Medu,2.750000,"Mother's education (0: none, 1: primary educat..."
5,Fedu,2.515823,"Father's education (0: none, 1: primary educat..."
6,traveltime,1.458861,"Home to school travel time (1: <15 min, 2: 15 ..."
7,studytime,2.050633,"Weekly study time (1: <2 hours, 2: 2 to 5 hour..."
8,failures,0.360759,Number of past class failures (from 0 to 3)
9,schoolsup,0.139241,Student receiving extra educational support (0...
10,famsup,0.613924,Student receiving family educational support (...
11,paid,0.455696,Student taking extra paid classes within the c...
12,activities,0.531646,Stdent taking part in extra-curricular activit...
13,nursery,0.800633,"Student has attended nursery school (0:no, 1:yes)"
14,higher,0.949367,"Student wants to get higher education (0:no, 1..."
15,internet,0.810127,"Student has internet access at home (0:no, 1:yes)"
16,romantic,0.322785,"Student is in a romantic relationship (0:no, 1..."
17,famrel,3.924051,Quality of family relationships (numeric: from...
18,freetime,3.243671,Free time after school (from 1 - very low to 5...
19,goout,3.098101,Going out with friends (from 1 - very low to 5...
20,Dalc,1.471519,Workday alcohol consumption (from 1 - very low...
21,Walc,2.306962,Weekend alcohol consumption (from 1 - very low...
22,health,3.547468,Current health status (from 1 - very bad to 5 ...
23,absences,5.750000,Number of school absences (actual number of ab...
24,guardian_father,0.253165,One-hot variable for student's guardian -- fat...
25,guardian_mother,0.658228,One-hot variable for student's guardian -- mot...
26,guardian_other,0.088608,One-hot variable for student's guardian -- nei...
27,Fjob_at_home,0.063291,One-hot variable for father's job -- at home
28,Fjob_health,0.047468,One-hot variable for father's job -- care related
29,Fjob_other,0.522152,One-hot variable for father's job -- other
30,Fjob_services,0.294304,One-hot variable for father's job -- civil ser...
31,Fjob_teacher,0.072785,One-hot variable for father's job -- teacher
32,reason_course,0.373418,One-hot variable for reason to choose this sch...
33,reason_home,0.265823,One-hot variable for reason to choose this sch...
34,reason_other,0.088608,One-hot variable for reason to choose this sch...
35,reason_reputation,0.272152,One-hot variable for reason to choose this sch...
36,Mjob_at_home,0.142405,One-hot variable for mothers's job -- at home
37,Mjob_health,0.088608,One-hot variable for mothers's job -- care rel...
38,Mjob_other,0.370253,One-hot variable for mothers's job -- other
39,Mjob_services,0.262658,One-hot variable for mothers's job -- civil se...
40,Mjob_teacher,0.136076,One-hot variable for mothers's job -- teacher

# Check finall preprocessed dataset

In [19]:
dataset_name="student"

train=pd.read_parquet(f"../data/{dataset_name}_dataset/train_cleaned.parquet")
test=pd.read_parquet(f"../data/{dataset_name}_dataset/test_cleaned.parquet")

In [21]:
train.head()

,sex,age,famsize,Pstatus,Medu,Fedu,traveltime,studytime,failures,schoolsup,...,reason_course,reason_home,reason_other,reason_reputation,Mjob_at_home,Mjob_health,Mjob_other,Mjob_services,Mjob_teacher,target
288,1,18,0,1,2,1,1,3,0,0,...,0,0,0,1,0,0,0,1,0,1
6,1,16,1,1,2,2,1,2,0,0,...,0,1,0,0,0,0,1,0,0,1
226,0,17,0,1,3,2,1,2,0,0,...,1,0,0,0,0,0,1,0,0,1
319,0,18,0,1,4,4,1,2,0,0,...,1,0,0,0,0,0,0,0,1,1
216,0,17,0,1,4,3,1,2,2,0,...,0,0,0,1,0,0,1,0,0,0